## Step 1: List Comprehensions

List Comprehensions provide a concise way to create lists. Let's create a list using the list comprehension method.

List comprehension offers a shorter syntax instead of using large **for** loops.

- Define an empty list
- Append items to the list using a traditional **for** loop

In [6]:
l = []
for i in range(10):
    l.append(i)

Now, let's display the list elements.

In [7]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Now, let's create a list with elements from 0 to 9 using the list comprehension method.

- Declare a list **l**
- Inside the square bracket, declare the variable **x** for iteration
- Each **x** iterates through the numbers 0 to 9 that are generated by **range() **function

In [8]:
l = [x for x in range(10)]

Now, let's display the list **l**.

In [9]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**Observation**

Numbers 0 to 9 is added to the list **l**.

Now, let's create a list with even numbers from 0 to 9 using list comprehension with a conditional statement.

- Define a variable **l**
- Inside the square bracket do the following:
     - Variable **x** iterates through numbers 0 to 9 
     - Check **x** is an even number using the **if** statement

In [10]:
l = [x for x in range(10) if x%2==0 ]

Now, let's see what is inside list **l**.

In [11]:
l

[0, 2, 4, 6, 8]

**Observation**

The **if** check make sures only even numbers are added to the list.

Create a new list of strings containing **odd** if the corresponding element in the list **l** is odd and **even** if it is even by using list comprehension with a conditional expression.

- Create a list **l** using the list comprehension method

In [12]:
l = [ x for x in range(10)]

- Create a list
- Add **odd** if **x** is an odd number
- Add **even** if **x** is an even number

In [13]:
string_l = [ 'odd' if x%2!=0 else 'even' for x in l ]

Now, let's display the list of strings.

In [14]:
string_l

['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']

**Observation**

Here, the list contains the elements even and odd, which are based on the numbers.

In [3]:
#zip:“pairs” up the elements of a number of lists, tuples, or other sequences, to create
#a list of tuples:
seq1 = ['teacher', 'girls', 'boys']

In [2]:
seq2 = ['one', 'two', 'three']

In [4]:
x = zip(seq1,seq2)

In [5]:
for i in x:
    print(i)

('teacher', 'one')
('girls', 'two')
('boys', 'three')

In [6]:
seq3 = [False, True]
x = zip(seq1, seq2, seq3)

In [7]:
for i in x:
    print(i)

('teacher', 'one', False)
('girls', 'two', True)

In [8]:
#simultaneously iterating over multiple sequences
for i, (a, b) in enumerate(zip(seq1, seq2)):
    print('%d: %s, %s' % (i, a, b))

0: teacher, one
1: girls, two
2: boys, three

In [9]:
some_list = ['foo', 'bar', 'baz']
mapping = dict((v, i) for i, v in enumerate(some_list))

In [10]:
mapping

{'foo': 0, 'bar': 1, 'baz': 2}